### ISSUE TITLE
Taking over gem

### ISSUE THREAD

**Issue by saizai** [thickpaddy/mysql_big_table_migration#7]
@thickpaddy It seems you've not touched this in a while, and it's not deployed to RubyGems.

How do you feel about me taking it over (w/ github.com/makeyourlaws) and publishing the gem w/ some improvements?

**Comment by thickpaddy** [comment]
Hi @saizai,

I'm no longer using MySQL, so I really don't mind if you want to fork the repo and publish it as a gem with improvements. However, the guys at Analog Analytics have put a fair bit of work into this over the past couple of years, and I'm guessing are still using it, so maybe they'd like to comment on this...

What  do you think @nickewing, @dzajic, @bsimpson ?

**Comment by thickpaddy** [comment]
Should also ask other contributors, @qxjit and @scottwillson - @saizai would like to take over maintenance of mysql_big_table_migration and publish it as a gem, sounds good to me, any thoughts?

**Comment by saizai** [comment]
I'd just like it to a) be in rubygems and b) have an active maintainer able
to accept pull requests etc. I'm willing to do it, but  defer to
 @nickewing, @dzajic, @bsimpson,  @qxjit or @scottwillson if they'd like
to. ;-)

**Comment by qxjit** [comment]
@saizai is ok with me!

**Comment by scottwillson** [comment]
Please take it over, @saizai. I'm sure the rest of the guys agree. Thanks!

**Comment by thickpaddy** [comment]
Excellent, go for it @saizai, let me know when to update the repo description and readme to point at your fork, and thanks btw :-)

**Comment by saizai** [comment]
@thickpaddy @scottwillson @qxjit  Done. :-)

https://github.com/MakeYourLaws/mysql_big_table_migration
https://rubygems.org/gems/mysql_big_table_migration
https://travis-ci.org/MakeYourLaws/mysql_big_table_migration

**Comment by thickpaddy** [comment]
Thanks @saizai, I've updated the description and readme to direct people to your fork. Nice to see old code get a new lease of life :-)

**Comment by saizai** [comment]
@thickpaddy And thanks for the gem. :-) It's very useful.
